name: Integração contínua de Java com Maven e SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Jobs do ambiente de desenvolvimento
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3

      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Compila o projeto com Maven
        run: mvn -B compile --file pom.xml

  # Jobs do ambiente de homologação
  build-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
    needs: build-dev
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Testa o projeto com Maven
        run: mvn -B test --file pom.xml

      # Cache dos pacotes do SonarCloud
      - name: Cache dos pacotes do SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache dos pacotes do Maven
      - name: Cache dos pacotes do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Verifica o projeto com Maven e Jacoco
      - name: Verifica o projeto com Maven e Jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=IanAkira_CalculadoraCI \
            -Dsonar.organization=ianakira \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # Jobs do ambiente de produção
  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-hmg
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3

      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      # Empacotamento do projeto com Maven
      - name: Empacota o projeto com Maven
        run: mvn -B package --file pom.xml -DskipTests

      # Cria uma pasta temporária de downloads de artefatos.
      - name: Crie uma pasta temporária de downloads de artefatos
        run: mkdir staging

      # Copia os artefatos a serem publicados na pasta temporária
      - name: Copia os artefatos a serem publicados na pasta temporária
        run: cp target/*jar-with-dependencies.jar staging

      # Usa Upload Artifact do GitHub Action
      - name: Usa Upload Artifact do GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
